In [2]:
import numpy as np
import pandas as pd

Exercise 1: Create and reshape a numpy array


In [4]:
arr1 = np.arange(1, 11)
print("The array created is : ",arr1)
arr1=arr1.reshape(2, 5)
print("Reshaped Array is :")
print(arr1)


The array created is :  [ 1  2  3  4  5  6  7  8  9 10]
Reshaped Array is :
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


Exercise 2: Extract elements between the 5th and 15th index


In [6]:
arr2 = np.arange(1, 21)
extracted_elements = arr2[5:16]
print("The extracted elements are:")
print(extracted_elements)

The extracted elements are:
[ 6  7  8  9 10 11 12 13 14 15 16]


Exercise 3: Create a Pandas series and add a new item

In [8]:
data = {'apples': 3, 'bananas': 2, 'oranges': 1}
series = pd.Series(data)
print("The panda seires is :\n",series)
series['pears'] = 4
print("\n The new updated pandas series is :")
print(series)


The panda seires is :
 apples     3
bananas    2
oranges    1
dtype: int64

 The new updated pandas series is :
apples     3
bananas    2
oranges    1
pears      4
dtype: int64


Exercise 4: Create a DataFrame with name, age, and gender columns


In [12]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Francis', 'Grace', 'Hannah', 'Issac', 'Jack'],
    'Age': [25, 32, 40, 29, 35, 41, 27, 30, 22, 45],
    'Gender': ['F', 'M', 'M', 'M', 'F', 'M', 'F', 'F', 'M', 'M']
}
df = pd.DataFrame(data)
print("\n The created dataframe is:\n")
print(df)


 The created dataframe is:

      Name  Age Gender
0    Alice   25      F
1      Bob   32      M
2  Charlie   40      M
3    David   29      M
4      Eva   35      F
5  Francis   41      M
6    Grace   27      F
7   Hannah   30      F
8    Issac   22      M
9     Jack   45      M


Exercise 5: Add a new column 'occupation'


In [14]:
occupations = ['Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer']
df['Occupation'] = occupations
print("\n The updated dataframe is :\n")
print(df)


 The updated dataframe is :

      Name  Age Gender  Occupation
0    Alice   25      F  Programmer
1      Bob   32      M     Manager
2  Charlie   40      M     Analyst
3    David   29      M  Programmer
4      Eva   35      F     Manager
5  Francis   41      M     Analyst
6    Grace   27      F  Programmer
7   Hannah   30      F     Manager
8    Issac   22      M     Analyst
9     Jack   45      M  Programmer


Exercise 6: Select rows where age >= 30


In [16]:
filtered_df = df[df['Age'] >= 30]
print("\n The dataframe after filtering rows with age >=30 is:\n")
print(filtered_df)



 The dataframe after filtering rows with age >=30 is:

      Name  Age Gender  Occupation
1      Bob   32      M     Manager
2  Charlie   40      M     Analyst
4      Eva   35      F     Manager
5  Francis   41      M     Analyst
7   Hannah   30      F     Manager
9     Jack   45      M  Programmer


Exercise 7: Convert to CSV and read it back


In [18]:
df.to_csv("data.csv", index=False)
print(pd.read_csv("data.csv"))


      Name  Age Gender  Occupation
0    Alice   25      F  Programmer
1      Bob   32      M     Manager
2  Charlie   40      M     Analyst
3    David   29      M  Programmer
4      Eva   35      F     Manager
5  Francis   41      M     Analyst
6    Grace   27      F  Programmer
7   Hannah   30      F     Manager
8    Issac   22      M     Analyst
9     Jack   45      M  Programmer
